#!/usr/bin/env bash
# scripts/generate_inventory.sh
# Reads the Terraform-provisioned instance IP and writes the Ansible inventory.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
TF_DIR="$REPO_ROOT/terraform"
INVENTORY_FILE="$REPO_ROOT/ansible/inventory/hosts.ini"

echo "==> Fetching public IP from Terraform state..."
cd "$TF_DIR"

INSTANCE_IP=$(terraform output -raw instance_public_ip 2>/dev/null)

if [[ -z "$INSTANCE_IP" ]]; then
  echo "ERROR: Could not retrieve instance_public_ip from Terraform output."
  echo "       Make sure you have run 'terraform apply' successfully."
  exit 1
fi

echo "==> Instance IP: $INSTANCE_IP"

cat > "$INVENTORY_FILE" <<EOF
# Auto-generated by scripts/generate_inventory.sh — do not edit manually.
[minecraft]
${INSTANCE_IP} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOF

echo "==> Inventory written to $INVENTORY_FILE"
